# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db90b7fa5cfc2e14b80d1f6fd14ddc70edb4c3e04c41f1d549678670aea3787d2782c2d0357498921146f920c50b45afbe78d723d009117631046e3263341e6e

test:
  secret_key_base: 1f05994a8d980e1c6d1f09d5797bb06292cade0b197d2bc346699c0d7d163ffa3ff70ae7767f4e2459ec1bb0dfc30bca196ee98d3c5d4709360e473a7deac2dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
